### ISSUE TITLE
when using TextVQA_VAL，meet torch.OutOfMemoryError

### ISSUE THREAD

**Issue by liuzhongling** [open-compass/VLMEvalKit#1021]
Here is the problem：
main/VLMEvalKit/vlmeval/vlm/qwen2_vl/modeling_qwen2_5_vl.py", line 273, in forward
    attn_weights = torch.matmul(q, k.transpose(1, 2)) / math.sqrt(self.head_dim)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 124.68 GiB. GPU 0 has a total capacity of 44.53 GiB of which 19.05 GiB is free. Including non-PyTorch memory, this process has 25.46 GiB memory in use. Of the allocated memory 24.89 GiB is allocated by PyTorch, and 73.93 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The model is qwen2_5_vl_7B.

when set attn_implementation='eager', test TextVQA_VAL is ok.

 When  attn_implementation='eager', it has torch.OutOfMemoryError after several epochs
But it has no torch.OutOfMemoryError when using other dataset MMbench，chartQA.

Does anyone know the reason，please help me，I try a lot but failed

**Comment by JVal123** [comment]
Hi! You don't have enough memory in your current CUDA GPU.

**Comment by liuzhongling** [comment]
> Hi! You don't have enough memory in your current CUDA GPU.

The batch_size is 1. The CUDA  memory will increase suddenly  after several epochs

**Comment by MaoSong2022** [comment]
I test qwen2.5-vl 7B with 80GB and it works fine. use 40GB memory  to test ~7B LVLM may causes OOM error, especially for MMMU and MathVista, so it is better to use a GPU with higher memory or use a quantized version of the model :)

**Comment by liuzhongling** [comment]
> I test qwen2.5-vl 7B with 80GB and it works fine. use 40GB memory to test ~7B LVLM may causes OOM error, especially for MMMU and MathVista, so it is better to use a GPU with higher memory or use a quantized version of the model :)

Thanks. It really helps
